name: Go Build and Deploy

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.5'  
        
    - name: Build the Go program
      run: go build -o go-db-manager .
    
    - name: Copy to server using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}  # adjust if your SSH port is different
        script: |
          ls
          scp go-db-manager ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/apps/go-db-manager
